version: 2.1
#.yml conf file
jobs:
  build:
    docker:
      - image: "cimg/node:16.10"
    steps:
      - node/install
      - node/install-yarn
      - checkout
      - install_client
      - install_server
      - run:
          name: Build Client
          command: yarn client:build
      - run:
          name: Build Server
          command: yarn server:build
  test:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - node/install-yarn
      - checkout
      - install_client
      - install_server
      - run: 
          name: Test Client 
          command: yarn client:test
      - run: 
          name: Test Server 
          command: yarn server:test
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - node/install-yarn
      - aws-cli/setup
      - eb/setup
      - checkout
      - install_client
      - install_server
      - run:
          name: Deploy Client
          command: yarn client:deploy
      - run:
          name: Deploy Server
          command: yarn server:deploy

workflows:
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test